#################################################################################
# PCIe Constraints for EAP_VU5p_PCIe
# @date:
# @author:
#################################################################################

#################################################################################
# General configuration
#################################################################################
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 63.8 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR NO [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE NO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

#################################################################################
# PCIe Interface gen3 *16
#################################################################################

set_property -dict {LOC AF2} [get_ports {pcie_rxp[0]}]
set_property -dict {LOC AF1} [get_ports {pcie_rxn[0]}]
set_property -dict {LOC AF7} [get_ports {pcie_txp[0]}]
set_property LOC GTYE4_CHANNEL_X1Y15 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[27].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AF6} [get_ports {pcie_txn[0]}]
set_property -dict {LOC AG4} [get_ports {pcie_rxp[1]}]
set_property -dict {LOC AG3} [get_ports {pcie_rxn[1]}]
set_property -dict {LOC AG9} [get_ports {pcie_txp[1]}]
set_property LOC GTYE4_CHANNEL_X1Y14 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[27].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AG8} [get_ports {pcie_txn[1]}]
set_property -dict {LOC AH2} [get_ports {pcie_rxp[2]}]
set_property -dict {LOC AH1} [get_ports {pcie_rxn[2]}]
set_property -dict {LOC AH7} [get_ports {pcie_txp[2]}]
set_property LOC GTYE4_CHANNEL_X1Y13 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[27].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AH6} [get_ports {pcie_txn[2]}]
set_property -dict {LOC AJ4} [get_ports {pcie_rxp[3]}]
set_property -dict {LOC AJ3} [get_ports {pcie_rxn[3]}]
set_property -dict {LOC AJ9} [get_ports {pcie_txp[3]}]
set_property LOC GTYE4_CHANNEL_X1Y12 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[27].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AJ8} [get_ports {pcie_txn[3]}]
set_property -dict {LOC AK2} [get_ports {pcie_rxp[4]}]
set_property -dict {LOC AK1} [get_ports {pcie_rxn[4]}]
set_property -dict {LOC AK7} [get_ports {pcie_txp[4]}]
set_property LOC GTYE4_CHANNEL_X1Y11 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[26].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AK6} [get_ports {pcie_txn[4]}]
set_property -dict {LOC AL4} [get_ports {pcie_rxp[5]}]
set_property -dict {LOC AL3} [get_ports {pcie_rxn[5]}]
set_property -dict {LOC AL9} [get_ports {pcie_txp[5]}]
set_property LOC GTYE4_CHANNEL_X1Y10 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[26].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AL8} [get_ports {pcie_txn[5]}]
set_property -dict {LOC AM2} [get_ports {pcie_rxp[6]}]
set_property -dict {LOC AM1} [get_ports {pcie_rxn[6]}]
set_property -dict {LOC AM7} [get_ports {pcie_txp[6]}]
set_property LOC GTYE4_CHANNEL_X1Y9 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[26].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AM6} [get_ports {pcie_txn[6]}]
set_property -dict {LOC AN4} [get_ports {pcie_rxp[7]}]
set_property -dict {LOC AN3} [get_ports {pcie_rxn[7]}]
set_property -dict {LOC AN9} [get_ports {pcie_txp[7]}]
set_property LOC GTYE4_CHANNEL_X1Y8 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[26].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AN8} [get_ports {pcie_txn[7]}]
set_property -dict {LOC AP2} [get_ports {pcie_rxp[8]}]
set_property -dict {LOC AP1} [get_ports {pcie_rxn[8]}]
set_property -dict {LOC AP7} [get_ports {pcie_txp[8]}]
set_property LOC GTYE4_CHANNEL_X1Y7 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[25].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AP6} [get_ports {pcie_txn[8]}]
set_property -dict {LOC AR4} [get_ports {pcie_rxp[9]}]
set_property -dict {LOC AR3} [get_ports {pcie_rxn[9]}]
set_property -dict {LOC AR9} [get_ports {pcie_txp[9]}]
set_property LOC GTYE4_CHANNEL_X1Y6 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[25].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AR8} [get_ports {pcie_txn[9]}]
set_property -dict {LOC AT2} [get_ports {pcie_rxp[10]}]
set_property -dict {LOC AT1} [get_ports {pcie_rxn[10]}]
set_property -dict {LOC AT7} [get_ports {pcie_txp[10]}]
set_property LOC GTYE4_CHANNEL_X1Y5 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[25].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AT6} [get_ports {pcie_txn[10]}]
set_property -dict {LOC AU4} [get_ports {pcie_rxp[11]}]
set_property -dict {LOC AU3} [get_ports {pcie_rxn[11]}]
set_property -dict {LOC AU9} [get_ports {pcie_txp[11]}]
set_property LOC GTYE4_CHANNEL_X1Y4 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[25].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AU8} [get_ports {pcie_txn[11]}]
set_property -dict {LOC AV2} [get_ports {pcie_rxp[12]}]
set_property -dict {LOC AV1} [get_ports {pcie_rxn[12]}]
set_property -dict {LOC AV7} [get_ports {pcie_txp[12]}]
set_property LOC GTYE4_CHANNEL_X1Y3 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[24].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC AV6} [get_ports {pcie_txn[12]}]
set_property -dict {LOC AW4} [get_ports {pcie_rxp[13]}]
set_property -dict {LOC AW3} [get_ports {pcie_rxn[13]}]
set_property -dict {LOC BB5} [get_ports {pcie_txp[13]}]
set_property LOC GTYE4_CHANNEL_X1Y2 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[24].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC BB4} [get_ports {pcie_txn[13]}]
set_property -dict {LOC BA2} [get_ports {pcie_rxp[14]}]
set_property -dict {LOC BA1} [get_ports {pcie_rxn[14]}]
set_property -dict {LOC BD5} [get_ports {pcie_txp[14]}]
set_property LOC GTYE4_CHANNEL_X1Y1 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[24].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC BD4} [get_ports {pcie_txn[14]}]
set_property -dict {LOC BC2} [get_ports {pcie_rxp[15]}]
set_property -dict {LOC BC1} [get_ports {pcie_rxn[15]}]
set_property -dict {LOC BF5} [get_ports {pcie_txp[15]}]
set_property LOC GTYE4_CHANNEL_X1Y0 [get_cells {pcie_core/inst/pcie4_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie4_uscale_plus_0_gt_i/inst/gen_gtwizard_gtye4_top.pcie4_uscale_plus_0_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[24].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST}]
set_property -dict {LOC BF4} [get_ports {pcie_txn[15]}]
set_property -dict {LOC AM11} [get_ports pcie_sys_clk_p]
set_property -dict {LOC AM10} [get_ports pcie_sys_clk_n]
set_property PACKAGE_PIN AR26 [get_ports pcie_sys_rst_n]
set_property IOSTANDARD LVCMOS12 [get_ports pcie_sys_rst_n]
set_property PULLTYPE PULLUP [get_ports pcie_sys_rst_n]

# 100 MHz MGT reference clock.  The PCIe IP supplies the generated user clocks.
create_clock -period 10.000 -name pcie_mgt_refclk_1 [get_ports pcie_sys_clk_p]

set_false_path -from [get_ports pcie_sys_rst_n]

#################################################################################
# System clocks
# 300 MHz (DDR 0)
#################################################################################
set_property -dict {LOC AW14 IOSTANDARD LVDS} [get_ports c0_sys_clk_p]
set_property -dict {LOC AW13 IOSTANDARD LVDS} [get_ports c0_sys_clk_n]
#set_property -dict {LOC C36 IOSTANDARD LVDS} [get_ports c1_sys_clk_p]
#set_property -dict {LOC C37 IOSTANDARD LVDS} [get_ports c1_sys_clk_n]

#################################################################################
# DDR4 C0
#################################################################################

set_property -dict {LOC AM14 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[0]}]
set_property -dict {LOC AV16 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[1]}]
set_property -dict {LOC AT13 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[2]}]
set_property -dict {LOC AP14 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[3]}]
set_property -dict {LOC AU16 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[4]}]
set_property -dict {LOC AU15 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[5]}]
set_property -dict {LOC AT15 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[6]}]
set_property -dict {LOC AR15 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[7]}]
set_property -dict {LOC AL15 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[8]}]
set_property -dict {LOC AP15 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[9]}]
set_property -dict {LOC AM15 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[10]}]
set_property -dict {LOC AR13 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[11]}]
set_property -dict {LOC AR16 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[12]}]
set_property -dict {LOC AN13 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[13]}]
set_property -dict {LOC AL14 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[14]}]
set_property -dict {LOC AN14 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[15]}]
set_property -dict {LOC AP13 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_adr[16]}]
set_property -dict {LOC AW16 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_ba[0]}]
set_property -dict {LOC AW15 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_ba[1]}]
set_property -dict {LOC AU13 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_c0_bg[0]}]
set_property -dict {LOC AU14 IOSTANDARD DIFF_SSTL12_DCI} [get_ports ddr4_c0_ck_t]
set_property -dict {LOC AV14 IOSTANDARD DIFF_SSTL12_DCI} [get_ports ddr4_c0_ck_c]
set_property -dict {LOC BB16 IOSTANDARD SSTL12_DCI} [get_ports ddr4_c0_cke]
set_property -dict {LOC BF13 IOSTANDARD SSTL12_DCI} [get_ports ddr4_c0_cs_n]
set_property -dict {LOC AV13 IOSTANDARD SSTL12_DCI} [get_ports ddr4_c0_act_n]
set_property -dict {LOC BB12 IOSTANDARD SSTL12_DCI} [get_ports ddr4_c0_odt]
set_property -dict {LOC AU19 IOSTANDARD LVCMOS12} [get_ports ddr4_c0_reset_n]

set_property -dict {LOC BF18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[0]}]
set_property -dict {LOC BE18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[1]}]
set_property -dict {LOC BF19 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[2]}]
set_property -dict {LOC BC17 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[3]}]
set_property -dict {LOC BC18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[4]}]
set_property -dict {LOC BB17 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[5]}]
set_property -dict {LOC BD18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[6]}]
set_property -dict {LOC BB19 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[7]}]
set_property -dict {LOC AY20 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[8]}]
set_property -dict {LOC AW19 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[9]}]
set_property -dict {LOC AW20 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[10]}]
set_property -dict {LOC AV18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[11]}]
set_property -dict {LOC AW18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[12]}]
set_property -dict {LOC BA18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[13]}]
set_property -dict {LOC AV19 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[14]}]
set_property -dict {LOC AY18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[15]}]
set_property -dict {LOC BC19 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_t[0]}]
set_property -dict {LOC BD19 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_c[0]}]
set_property -dict {LOC AV21 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_t[1]}]
set_property -dict {LOC AW21 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_c[1]}]
set_property -dict {LOC BE17 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dm_dbi_n[0]}]
set_property -dict {LOC AY17 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dm_dbi_n[1]}]
#set_property -dict {LOC BE17 IOSTANDARD POD12_DCI}       [get_ports {ddr4_c0_dm_n[0]}]
#set_property -dict {LOC AY17 IOSTANDARD POD12_DCI}       [get_ports {ddr4_c0_dm_n[1]}]

set_property -dict {LOC AP18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[16]}]
set_property -dict {LOC AR20 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[17]}]
set_property -dict {LOC AT20 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[18]}]
set_property -dict {LOC AT18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[19]}]
set_property -dict {LOC AP20 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[20]}]
set_property -dict {LOC AR18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[21]}]
set_property -dict {LOC AU20 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[22]}]
set_property -dict {LOC AU17 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[23]}]
set_property -dict {LOC AM16 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[24]}]
set_property -dict {LOC AP19 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[25]}]
set_property -dict {LOC AN16 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[26]}]
set_property -dict {LOC AN19 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[27]}]
set_property -dict {LOC AM19 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[28]}]
set_property -dict {LOC AL20 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[29]}]
set_property -dict {LOC AL19 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[30]}]
set_property -dict {LOC AM20 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[31]}]
set_property -dict {LOC AR17 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_t[2]}]
set_property -dict {LOC AT17 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_c[2]}]
set_property -dict {LOC AL17 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_t[3]}]
set_property -dict {LOC AM17 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_c[3]}]
set_property -dict {LOC AT19 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dm_dbi_n[2]}]
set_property -dict {LOC AN18 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dm_dbi_n[3]}]
#set_property -dict {LOC AT19 IOSTANDARD POD12_DCI}       [get_ports {ddr4_c0_dm_n[2]}]
#set_property -dict {LOC AN18 IOSTANDARD POD12_DCI}       [get_ports {ddr4_c0_dm_n[3]}]

set_property -dict {LOC BF15 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[32]}]
set_property -dict {LOC BC14 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[33]}]
set_property -dict {LOC BD16 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[34]}]
set_property -dict {LOC BD14 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[35]}]
set_property -dict {LOC BE15 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[36]}]
set_property -dict {LOC BD15 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[37]}]
set_property -dict {LOC BC13 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[38]}]
set_property -dict {LOC BE16 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[39]}]
set_property -dict {LOC AY12 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[40]}]
set_property -dict {LOC AY11 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[41]}]
set_property -dict {LOC BA13 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[42]}]
set_property -dict {LOC AY15 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[43]}]
set_property -dict {LOC BA15 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[44]}]
set_property -dict {LOC BA14 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[45]}]
set_property -dict {LOC AY16 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[46]}]
set_property -dict {LOC AY13 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[47]}]
set_property -dict {LOC BD13 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_t[4]}]
set_property -dict {LOC BE13 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_c[4]}]
set_property -dict {LOC BB15 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_t[5]}]
set_property -dict {LOC BB14 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_c[5]}]
set_property -dict {LOC BF14 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dm_dbi_n[4]}]
set_property -dict {LOC BA12 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dm_dbi_n[5]}]
#set_property -dict {LOC BF14 IOSTANDARD POD12_DCI}       [get_ports {ddr4_c0_dm_n[4]}]
#set_property -dict {LOC BA12 IOSTANDARD POD12_DCI}       [get_ports {ddr4_c0_dm_n[5]}]

set_property -dict {LOC BA28 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[48]}]
set_property -dict {LOC BB26 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[49]}]
set_property -dict {LOC AW28 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[50]}]
set_property -dict {LOC AY28 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[51]}]
set_property -dict {LOC BA27 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[52]}]
set_property -dict {LOC BB27 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[53]}]
set_property -dict {LOC AY27 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[54]}]
set_property -dict {LOC AY26 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[55]}]
set_property -dict {LOC AU26 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[56]}]
set_property -dict {LOC AV27 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[57]}]
set_property -dict {LOC AR28 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[58]}]
set_property -dict {LOC AU27 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[59]}]
set_property -dict {LOC AT27 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[60]}]
set_property -dict {LOC AV28 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[61]}]
set_property -dict {LOC AT28 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[62]}]
set_property -dict {LOC AR27 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dq[63]}]
set_property -dict {LOC AW25 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_t[6]}]
set_property -dict {LOC AY25 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_c[6]}]
set_property -dict {LOC AR25 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_t[7]}]
set_property -dict {LOC AT25 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_c[7]}]
set_property -dict {LOC BA25 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dm_dbi_n[6]}]
set_property -dict {LOC AV26 IOSTANDARD POD12_DCI} [get_ports {ddr4_c0_dm_dbi_n[7]}]
#set_property -dict {LOC BA25 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dm_n[6]}]
#set_property -dict {LOC AV26 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dm_n[7]}]

#set_property -dict {LOC BF27 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dq[64]}]
#set_property -dict {LOC BF25 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dq[65]}]
#set_property -dict {LOC BD28 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dq[66]}]
#set_property -dict {LOC BE28 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dq[67]}]
#set_property -dict {LOC BC26 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dq[68]}]
#set_property -dict {LOC BE25 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dq[69]}]
#set_property -dict {LOC BE27 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dq[70]}]
#set_property -dict {LOC BC27 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dq[71]}]
#set_property -dict {LOC BD26 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_t[8]}]
#set_property -dict {LOC BE26 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_c0_dqs_c[8]}]
#set_property -dict {LOC BF28 IOSTANDARD POD12_DCI}      [get_ports {ddr4_c0_dm_dbi_n[8]}]


